name: 自动签到

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    
    steps:
    - name: 获取代码
      uses: actions/checkout@v4
      
    - name: 设置Node.js环境
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: 清理并安装依赖
      run: |
        rm -rf node_modules
        rm -f package-lock.json
        npm install
        
    - name: 运行签到脚本
      env:
        WEBSITE_USERNAME: ${{ secrets.WEBSITE_USERNAME }}
        WEBSITE_PASSWORD: ${{ secrets.WEBSITE_PASSWORD }}
      run: node checkin.js
      
    - name: 上传结果
      uses: actions/upload-artifact@v4
      with:
        name: checkin-result
        path: |
          *.png
          *.txt
        retention-days: 7
